# Generated by Django 4.1.7 on 2023-02-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_author_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
