# Generated by Django 4.1.7 on 2023-03-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_client_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
